- name: "Create user bat config dir at '{{ user_bat_config_dir }}'"
  ansible.builtin.file:
    path: "{{ user_bat_config_dir }}"
    state: directory
    owner: "{{ bat_user_name }}"
    group: "{{ bat_user_name }}"
    mode: '755'
  vars:
    user_bat_config_dir: "{{ bat_user_config_file_path | dirname }}"
  become: true
  become_user: root

- name: "Configure user bat settings in '{{ bat_user_config_file_path }}'"
  ansible.builtin.template:
    dest: "{{ bat_user_config_file_path }}"
    src: "config.j2"
    owner: "{{ bat_user_name }}"
    group: "{{ bat_user_name }}"
    mode: '644'
    force: true
  become: true
  become_user: root

